# Generated by Django 4.0.4 on 2022-05-04 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('apartment_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адресы',
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(choices=[('HP', 'Headphones'), ('PH', 'Phones'), ('AC', 'Accessories'), ('TV', 'Television'), ('UN', 'Undefined')], default='UN', max_length=2)),
                ('file', models.FileField(blank=True, null=True, upload_to='images')),
                ('file_format', models.CharField(choices=[('IMG', 'Image'), ('FL', 'File'), ('UN', 'Undefined')], default='UN', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SportItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='No title', max_length=100, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, default='no description', null=True)),
                ('manufacturer', models.TextField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.filemodel')),
                ('storage_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.address')),
            ],
            options={
                'verbose_name': 'Спортивный инвентарь',
                'verbose_name_plural': 'Спортивный инвентарь',
            },
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='No title', max_length=100, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, default='no description', null=True)),
                ('category', models.CharField(choices=[('HP', 'Headphones'), ('PH', 'Phones'), ('AC', 'Accessories'), ('TV', 'Television'), ('UN', 'Undefined')], default='UN', max_length=2)),
                ('manufacturer', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.filemodel')),
                ('storage_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.address')),
            ],
            options={
                'verbose_name': 'Электроника',
                'verbose_name_plural': 'Электроники',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='No title', max_length=100, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, default='no description', null=True)),
                ('author', models.TextField(blank=True, max_length=200, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.filemodel')),
                ('storage_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.address')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.books')),
                ('electronics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.electronics')),
                ('sport_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sportitems')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
